### PR TITLE
Fix .all-contributorsrc

### PR DESCRIPTION
**Pull request by danieltott**
In a previous merge this file had gotten mangled

### CODE REVIEW

**Comment by danieltott** [comment]
@all-contributors add @danieltott for docs

**Comment by CBID2** [comment]
@all-contributors add @danieltott for docs

**Comment by danieltott** [comment]
@CBID2 you'll need to merge this one in for it to work

**Comment by danieltott** [comment]
Then I'd like to try the comment to see what happens when a non-maintainer does it

**Comment by CBID2** [comment]
Ok so should I comment @danieltott?

**Comment by danieltott** [comment]
@all-contributors add @danieltott for docs

**Pull request merged**
